# TECP Reference UI - Fly.io Configuration
app = "tecp-ui"
primary_region = "sjc"

[build]
  dockerfile = "../Dockerfile.ui"

[env]
  VITE_TECP_LOG_URL = "https://tecp-log.fly.dev"
  VITE_TECP_DEMO_URL = "https://tecp-demo.fly.dev"
  VITE_TECP_VERIFIER_URL = "https://tecp-verifier.fly.dev"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  protocol = "http"
  restart_limit = 0
  timeout = "5s"
